"""add phone_number column to users table

Revision ID: 33a1da3314c9
Revises: 9af2f2a0b32b
Create Date: 2023-10-27 12:06:03.560153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33a1da3314c9"
down_revision: Union[str, None] = "9af2f2a0b32b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
