name: buid and deploy code
on: [push, pull_requests]

jobs:
  job1:
    run-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: say hi jeeva
        run: echo "hello jeeva"
