name: build and deploy code
on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_NAME: fastapi-blog
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: JsttU1324
      SECRET_KEY: abdabcd08f82987b64dc11972ad8b3a4beaf6c6452351fe57548a2b0fe21290f
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: Install python version 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: update pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest
